spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  file:
    path: ${SIYUBAO_USER_LOG_DIR:${user.home}/.siyubao/logs}
  level:
    root: INFO

admin:
  base-url: ${SIYUBAO_ADMIN_BASE_URL:http://localhost:6943}
